spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:javamongo
    username: sa
    password:

  batch:
    jdbc:
      initialize-schema: always
mongo:
  uri: mongodb://localhost:27017/javamongo
  database: javamongo